### ISSUE TITLE
关于源码

### ISSUE THREAD

**Issue by yoho131** [gaobb/OneNIP#2]
读了作者大大的论文之后，只感觉受益良多，请问什么时候能开源呢

**Comment by gaobb** [comment]
hi, @yoho131 

Sorry for the delayed response. Thank you very much for your interest in our work.

The source code and pre-trained models of our OneNIP are now available and you can use them freely. If you have any questions, please don't hesitate to contact me.

Thanks for your attention.

Best Regards!
Bin-Bin
