### ISSUE TITLE
The code implementation of TransformerDecoderLayer is not the same as described in the paper

### ISSUE THREAD

**Issue by strawberrylazy** [gaobb/OneNIP#6]
Thank you for the author's work. After reading the paper and the code, I have a question here: The figure in the paper shows that feats-prompt cross-attn is used, but feats-prompt cross-attn is not used in the code. In fact, there is a feats-prompt cross-attn module in the network, but after the feature goes through this module, the output feature is not used, why is this?
![image](https://github.com/user-attachments/assets/606f91bf-94df-4153-8734-e476e3051ddb)
![image](https://github.com/user-attachments/assets/ed1eded8-ca36-4fe9-8025-f77f86a1fbaa)

**Comment by gaobb** [comment]
hi, @strawberrylazy 

Sorry for the late reply, as I have been busy with other projects recently.

Thank you very much for pointing out this issue, I have fixed the bug, please see the updated code.

Best Regards,
Bin-Bin
